### PR TITLE
Fix migration stub to use configurations for database driver

### PR DESCRIPTION
**Pull request by the-great-tao**
This allows us to change database driver configuration before calling "php artisan migrate".

### CODE REVIEW

**Comment by anteriovieira** [comment]
Ping @quetzyg

**Comment by quetzyg** [comment]
Nice spotted @the-great-tao,

I would just ask you to update your pull request to include the same logic in the `down()` method.

```php
    public function down()
    {
        Schema::connection(config('audit.drivers.database.connection'))
            ->drop(config('audit.drivers.database.table'));
    }
```

**Comment by the-great-tao** [comment]
Done, please check. Thank you!

**Comment by anteriovieira** [comment]
@the-great-tao  thanks for this PR.

**Pull request merged**
