### PR TITLE
Use FQN instead of alias to fix phpstan internal error

### PR DESCRIPTION
**Pull request by SanderMuller**
Fixes an phpstan (Larastan) internal error which we only started getting after #798 

image

### CODE REVIEW

**Comment by parallels999** [comment]
weird, there is no `newEloquentBuilder` on this package

Try on [Contracts/Audit.php](https://github.com/owen-it/laravel-auditing/blob/master/src/Contracts/Audit.php)  something like
```php
namespace OwenIt\Auditing\Contracts;

** 
 * @mixin \Illuminate\Database\Eloquent\Model
 */
interface Audit
{

```

**Comment by parallels999** [comment]
Did you test this fix??

**Comment by SanderMuller** [comment]
> Did you test this fix??

`./vendor/bin/phpstan analyse` (and `./vendor/bin/phpstan analyse --debug`) are green after change, at least in the project where it isn't workings since [v13.5.0](https://github.com/owen-it/laravel-auditing/releases/tag/v13.5.0)

**Review by MortenDHansen — APPROVED** [review]

**Comment by MortenDHansen** [comment]
I don't see any difference, so if we make phpstan happy, then why not 😄

**Comment by erikn69** [comment]
@SanderMuller hi, it is a rollback to https://github.com/owen-it/laravel-auditing/pull/734
Please try https://github.com/owen-it/laravel-auditing/pull/809

**Comment by SanderMuller** [comment]
> @SanderMuller hi, it is a rollback to #734 Please try #809

Weird, #809 again results in the same error. 
image

I have no clue why, though. Will see if I can find something. It's fine by me to merge #809, we can skip the version update until we have found a solution for this.

**Comment by aglipanci** [comment]
@SanderMuller that change was introduced by me here https://github.com/owen-it/laravel-auditing/pull/798 because I was getting this error from larastan, now that you changed it back I am still getting it

Screenshot 2023-06-20 at 10 39 31

**Comment by stefro** [comment]
I can confirm that I also have the same issues as @aglipanci mentioned above since this week.

**Comment by digistorm** [comment]
I just came across the same issue and put a PR for the fix.
- Bug report: #843 
- PR: #842

**Pull request merged**
