### PR TITLE
Tiny fix

### PR DESCRIPTION
**Pull request by SERVANT14**

### CODE REVIEW

**Comment by anteriovieira** [comment]
Thank you, your contribution is most welcome. I need to refactor the documentation but my English is not so good.

**Comment by SERVANT14** [comment]
I'd be glad to help if you want.

**Comment by anteriovieira** [comment]
:smiley:   would be great, I am very happy with your help. Welcome to the team, feel free to make changes. Thanks again.

**Comment by SERVANT14** [comment]
Okay, I will try to take some time this week and read through the readme and improve it if I can :). I think one thing the readme needs is an explanation of how this package differs from the revisionable package. What's the motivation for the package when revisionable already exists?

**Comment by anteriovieira** [comment]
@SERVANT14 I agree with you.

Initially it was the version, revisionable was for version 4.0 of laravel. But that's not relevant. I will listed below some points that we highlight:

* The auditing records all model changes to an single record, becoming more flexible handling of logs.
* The auditing values the quick and easy implementation
* The auditing allows the customization of the log messages, avoiding unnecessary logic in views.

:) I'll get a better look on the characteristics and will listing here.

If it is comfortable for you we could use gmail to go arguing about the improvements.

**Pull request merged**
