### PR TITLE
Fix iterating over all audits, if audible model is not resolved

### PR DESCRIPTION
**Pull request by mikebronner**
Possible fix for #206, not tested for side-effects, but seems to run OK with local dataset.

### CODE REVIEW

**Comment by anteriovieira** [comment]
Ping @quetzyg

**Comment by quetzyg** [comment]
Hi @mikebronner,

While I understand the problem (`Auditable` morphTo relation not being loaded), I'm unable to reproduce it.

I currently have the `audits` table with quite a few entries from several model types and I'm doing:
```php
    foreach (\OwenIt\Auditing\Models\Audit::all() as $audit) {
        dump($audit->getModified());
    }
```
I'm able to get everything as expected, never getting the issue described in #206.

Can you show me how you're running into it?

**Comment by quetzyg** [comment]
Actually, I just read @truonggiangdao's comment about deletion, which makes total sense now.

**Comment by mikebronner** [comment]
Thanks for merging! Yea, I'm pretty sure the issue was caused by deleting database entries. Sorry I wasn't more explicit in my description :). (Was focused on the symptom, instead of also researching the cause.)

**Comment by quetzyg** [comment]
Not a problem mate, thank you both for reporting!

**Pull request merged**
