### PR TITLE
Make queued audits feature opt-in

### PR DESCRIPTION
**Pull request by erikn69**

### CODE REVIEW

**Review by MortenDHansen — APPROVED** [review]

**Comment by MortenDHansen** [comment]
Seems like a good fix. Im not sure if there is something we should take into account before releasing it? (@Orrison ? )

**Comment by Orrison** [comment]
This should do the trick I believe.

**Review by Orrison — APPROVED** [review]

**Comment by parallels999** [comment]
I didn't know how to solve my problem, but with this at least I don't have to go back to a previous version

**Review by parallels999 — APPROVED** [review]

**Review by angeljqv — APPROVED** [review]

**Comment by cosmastech** [comment]
Isn't this technically making it "opt-out" since the default is now to queue where it wasn't previously?

**Pull request merged**
