### PR TITLE
Upgrade to Laravel 7

### PR DESCRIPTION
**Pull request by RossAHC**

### CODE REVIEW

**Comment by cwilby** [comment]
@MrReeds does @anteriovieira need to approve these changes to merge the PR?

**Comment by MrReeds** [comment]
> @MrReeds does @anteriovieira need to approve these changes to merge the PR?

seems so, only authorized people are allowed

**Comment by MammutAlex** [comment]
@anteriovieira Hi,
I don't mean to push you but this is the only package holding me back from upgrading my application to Laravel 7.x

Do you happen to know when you can approve the request?

**Comment by thierrydrc** [comment]
Up please !

**Comment by cwilby** [comment]
Switched to https://altek.gitlab.io/accountant/.  It's a fork by a maintainer that already supports L7 and stores changes differently.

**Comment by aglipanci** [comment]
> Switched to https://altek.gitlab.io/accountant/. It's a fork by a maintainer that already supports L7 and stores changes differently.

Can you elaborate? Is it easy to migrate?

**Comment by reliq** [comment]
Hmmm. What's happening here is interesting... 👀

**Comment by cwilby** [comment]
@aglipanci sorry I should have been more clear - I'm starting a new project without existing records.

If you are already using the Auditing package, migrating will be tricky as the new library digitally signs ledger entries.

**Comment by cwilby** [comment]
@aglipanci more here https://gitlab.com/altek/accountant/-/issues/26

**Comment by icaroscherma** [comment]
Guys, **only the Maintainers** can approve this. If you are "desperate" to use L7 with this package, use @efriandika solution. Add this to your `composer.json` :
```JSON
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/RossAHC/laravel-auditing"
    }
],
"require": {
    "owen-it/laravel-auditing": "dev-laravel-7"
},
```

**Comment by mpyw** [comment]
What's blocking it?

**Comment by icaroscherma** [comment]
> What's blocking it?

`Merging is blocked` means that it's open-sorce but not free-software.
Merging will not be automatic after CI's approval, it relies on the Mainatainer's (human) approval.
Since none of us (so far) it's an Official Maintainer of this repository, we have no power here.

**Comment by mpyw** [comment]
@icaroscherma Sure, I know. My question is "Why the maintainers are pending this PR?"

**Comment by icaroscherma** [comment]
> @icaroscherma Sure, I know. My question is "Why the maintainers are pending this PR?"

This is a good question, since he's commiting non-stop. (He already had 11 commits today)

@anteriovieira Aprova o PR aqui jovem =(

**Comment by backstageel** [comment]
+

**Comment by afroty** [comment]
Any updates?

**Comment by RossAHC** [comment]
@anteriovieira Is there anything specific that needs to be changed with this PR for it to be approved? If it's because CI checks haven't been reported it might mean there's a need to remove the outdated check in the protected branch settings in the repository settings.

**Comment by icaroscherma** [comment]
> @anteriovieira Is there anything specific that needs to be changed with this PR for it to be approved? If it's because CI checks haven't been reported it might mean there's a need to remove the outdated check in the protected branch settings in the repository settings.

I've emailed him yesterday and I got no replies so far. :/
But IMHO, I don't think it's an issue with your PR.

**Comment by garbinmarcelo** [comment]
Teria alguma previsão para o suporte ao Laravel 7? :smiley: :beers:

---

Would you have an estimated date for Laravel 7 support?

**Comment by mpyw** [comment]
@anteriovieira  If you are busy, why don't you recruit maintainers from contributors?

**Comment by cwilby** [comment]
@mpyw I'm not sure "busy" is accurate, maybe a dusty notifications icon?

image

**Comment by mpyw** [comment]
@cwilby I see. Anyway, if the author abandon maintaining, it's just a matter of time that a fork will be registered to Packagist...

**Comment by mpyw** [comment]
@RossAHC Would you consider registering to Packagist if the PR will have been stale for several weeks from now?

**Comment by efriandika** [comment]
I agree with @cwilby ..
Probably we can contact to @anteriovieira email directly wether he have a posibility to merge this PR or no. If no, we can go ahead creating a new organization to maintain this one...
I think this library is amazing, we should make this keep alive.

**Comment by cwilby** [comment]
@efriandika The concern there is creating another fork of the same project.  This has been an issue since the [original maintainer](https://github.com/owen-it/laravel-auditing/graphs/contributors) (@quetzyg)  forked this project and made [Accountant](https://gitlab.com/altek/accountant) - which has gained from refactoring this project.

Additionally, there is [progress](https://gitlab.com/altek/accountant/-/issues/26) on a [migration script](https://gist.github.com/leeovery/793a0332c87a12e6bb370035f206d08a) to convert this package.

That being said, would be great to have this branch merged 🤓

**Comment by MrReeds** [comment]
I wrote him email on 14th, no reply. Mentioned that maybe he could add maintainers if he is too busy

**Comment by jtomek** [comment]
I just wrote him on LinkedIn.

**Comment by anteriovieira** [comment]
Guys I'm sorry about that. I will go back to work on the package again.

**Pull request merged**
