### PR TITLE
fix: diff attributes casting

### PR DESCRIPTION
**Pull request by christianbayer**
Solves #568, related to #216.

### CODE REVIEW

**Comment by MortenDHansen** [comment]
I don't actually think this is still an issue. 
The following test seems to cover the case

```
    /**
     * @test
     * @return void
     */
    public function itHandlesJsonColumnsCorrectly()
    {
        $article = factory(Article::class)->create(['config' => ['articleIsGood' => true, 'authorsJob' => 'vampire']]);
        $article->refresh();

        $article->config = ['articleIsGood' => false, 'authorsJob' => 'vampire'];
        $article->save();

        /** @var Audit $audit */
        $audit = $article->audits()->skip(1)->first();

        $this->assertSame(false, $audit->getModified()['config']['new']['articleIsGood']);
        $this->assertSame(true, $audit->getModified()['config']['old']['articleIsGood']);
    }
```

**Comment by MortenDHansen** [comment]
I think the issue is resolved 

The following test should cover it.
```
    public function itHandlesJsonColumnsCorrectly()
    {
        $article = factory(Article::class)->create(['config' => ['articleIsGood' => true, 'authorsJob' => 'vampire']]);
        $article->refresh();

        $article->config = ['articleIsGood' => false, 'authorsJob' => 'vampire'];
        $article->save();

        /** @var Audit $audit */
        $audit = $article->audits()->skip(1)->first();

        $this->assertSame(false, $audit->getModified()['config']['new']['articleIsGood']);
        $this->assertSame(true, $audit->getModified()['config']['old']['articleIsGood']);
    }
```

I also tried executing this:
```
    /**
     * @test
     * @return void
     */
    public function itCastsJson()
    {
        $article = factory(Article::class)->create(['reviewed' => false]);

        $article->reviewed = true;
        $article->save();

        $audit = $article->audits()->get()->last();
        $this->assertEquals('{"reviewed":false}', json_encode($audit->old_values));
        $this->assertEquals('{"reviewed":true}', json_encode($audit->new_values));
    }
```

**Comment by christianbayer** [comment]
This problem still exists. Maybe the test case is not covering all possibilities. Without the patch I'm proposing in this PR, the cast is not being applied. See my comment at https://github.com/owen-it/laravel-auditing/issues/568#issuecomment-1042514492.

**Comment by MortenDHansen** [comment]
> This problem still exists. Maybe the test case is not covering all possibilities. Without the patch I'm proposing in this PR, the cast is not being applied. See my comment at [#568 (comment)](https://github.com/owen-it/laravel-auditing/issues/568#issuecomment-1042514492).

Any chance you can help me with a scenario where it fails so that i can cover it with a test 😄

**Comment by MortenDHansen** [comment]
Just to be clear, problem in the issue is that the old values and new values are different, which i can't reproduce, but i may be missing something. What we expect in the columns in the database is the raw representation. In this case 0 or 1 (boolean in mysql). When fetching the record using ->getModified() we would expect that to run through the cast. The values stored in the audits table are not supposed to be cast before they are stored.

**Comment by christianbayer** [comment]
I'll try to explain my scenario. Just for a background, we have a Laravel 8 application with MariaDB 10.3 and Auditing v12.0. For example, we have a `users` table:
```
Schema::table('users', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('name', 255);
    $table->boolean('active')->default(1);
});
```
And a user model:
```
class User implements AuditableContract
{
    use Auditable;
    protected $fillable = [
        'name',
        'active',
    ];
    protected $casts = [
        'active' => 'boolean',
    ];
}
```
An important detail: the `boolean` defined in the migration does not really creates a boolean column in the database. Instead it is a tinyint column. I don't know why, but that's the way Laravel handles it.

Anyway. If I create a User called Ana with active="true", the Audit will store: `old` as `[]` and `new` as `{name: "Ana", active: "true"}`. Now, I will just open the form, click save (without changing nothing, still Ana, still active), and the Audit will pick a change of `old` as `{active: 1}` and `new` as `{active: true}`.

Why? **Because `$this->original` does not cast any attributes, but the `$this->getOriginal()` does.** 

That's my use case, that's my issue. After changing what I've proposed in this PR, this issue has gone away.

If you need more info, or anything else I can help with, please let me know.

**Comment by MortenDHansen** [comment]
Allright. Thanks.

There is no boolean in mysql (mariadb). It's just a tinyint field. The underlying value will be 0,1 or null. 

The laravel-auditing package will take the user supplied values in changes (before write) and the values from the model (fetched) out of the Eloquent model, but based on the getDirty(). In Laravel, that uses Laravels "originalsEquivalent()" method analyzing the casts (and various cases). What is written by audit is determined by the compared cast values from eloquent, but the audit content is the users values.

Basically, laravel auditing will work "as intended", but using the users input for what is supplied against the existing record. I see that it is a problem when the existing column is a boolean it can be written arbitrarily into the serialized json, but i can't find a problem where a wrong update will occur. I've tried several approaches. In any case, that would be an Eloquent problem since the update is triggered by Eloquent, not laravel-audit.

```
    /**
     * @test
     * @return void
     */
    public function itCastsJson()
    {
        $article = factory(Article::class)->create(['reviewed' => true]);

        // Set true to true
        $article->reviewed = true;
        $article->save();

        // set true to string true (evaluates to true)
        $article->reviewed = "true";
        $article->save();

        // Set to database equivalent of true (1)
        $article->reviewed = 1;
        $article->save();

        // Set to string false (evaluates to true)
        $article->reviewed = "false";
        $article->save();

        // Check that none of the 4 previous saves spawned an audit record (nothing actually changed)
        $audits = $article->audits()->get();
        $this->assertCount(1, $audits);

        // Assert the audit new value is true as created
        $audit = $article->audits()->get()->last();
        $this->assertEquals(["new" => true], $audit->getModified()['reviewed']);
        $article->refresh(); // reset experiments

        // Change the value of the field
        $article->reviewed = false;
        $article->save();

        $audit = $article->audits()->get()->last();
        $this->assertEquals('updated', $audit->event);

        // Values of getModified are correct booleans
        $this->assertEquals(['new' => false, 'old' => true], $audit->getModified()['reviewed']);


        // Change the value of the field, but with a different type
        $article->reviewed = 'banana'; // This is a bad way to write a boolean value since any string will be true
        $article->save();

        // assert new value is user input value, and old is still boolean type.
        $audit = $article->audits()->get()->last();
        $this->assertEquals(["new" => true, "old" => false], $audit->getModified()['reviewed']);
    }
```

Article::class casts reviewed to boolean

In terms of the PR, it would be a breaking change so i can't merge it as is. The system should interpret the values based on casts when fetching the content. Not on write. I see that the json serializer however may act in unpredictable ways when storing the json, but I am still not able to reproduce the problem.

**Comment by aromka** [comment]
Running into a similar issue where it creates audits for changes from `{ value: 0 }` to `{ value: false }`

Screenshot_430

Is there a method where these values can be compared and removed the audits?

**Comment by parallels999** [comment]
@aromka  try casting
```php
protected $casts = ['value'=>'integer'];
```
Also try `transformAudit`
https://laravel-auditing.com/guide/audit-transformation.html

**Pull request closed without merging**
