### PR TITLE
Update default guards to match Laravel changes

### PR DESCRIPTION
**Pull request by falko189**
Update the default api guard to be sanctum following the update on laravel here
https://github.com/laravel/laravel/commit/226d1bfc3c774e24a79e68e9f1264b5ca359551f#diff-66a4eb6caa45de87ad409f2f5f2d5e7dd30aacd12de32af921aa32317cf9b2e2L45

### CODE REVIEW

**Comment by anteriovieira** [comment]
related https://github.com/laravel/laravel/pull/5663

**Comment by falko189** [comment]
That's a fair point, we could release a major version with this as breaking change. But at the very least we should mention it in the Readme that this is a known issue 👍🏻  Let me know and I'll put together something

**Comment by MortenDHansen** [comment]
Hi guys, just spitballing here, but could this be a solution?

https://github.com/owen-it/laravel-auditing/pull/695

Basically we skip the guard if it can't be resolved and for new installs we leave the config array empty. Upon running the user resolver it will fall back to the default configured in laravel auth.php

**Comment by falko189** [comment]
Yep your solution is much more elegant and should cover old laravel versions :) I'll close this off! thanks

**Pull request closed without merging**
