### PR TITLE
Test adding PHPStan to mergeflow

### PR DESCRIPTION
**Pull request by MortenDHansen**
see #808

### CODE REVIEW

**Comment by MortenDHansen** [comment]
@erikn69 
This is one of those things where i am not sure why we are doing this. 

1. Is it important for our users? - and why? 
2. Is it right to add these changes to the current version? 

I mean, i like types and all that, but it does not seem like our codebase is ready for this.
... or am i just to cautious.

**Comment by erikn69** [comment]
> Is it important for our users? - and why?

It is important to prevent possible bugs

> Is it right to add these changes to the current version?

it passes the tests correctly, It seems to me that there are no breaking changes, but I would feel safer for v14

but I think that it should not be put in the workflow, I am going to do a PR to show you

**Comment by MortenDHansen** [comment]
> but I think that it should not be put in the tests workflow, I am going to do a PR to show you

I like that version better :)

**Comment by MortenDHansen** [comment]
@erikn69 - changed to v14 branch. If you approve, well make it so :)

**Comment by erikn69** [comment]
Hi @MortenDHansen I noticed that the tests are not running, something broke or it is because it is the dev branch

**Pull request merged**
