### PR TITLE
Laravel 11.x Support

### LINKED ISSUE #907: Implement support for Laravel 11.x.
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 11.x
| Package version   | -
| PHP version       | 8.2 / 8.3

#### Actual Behaviour

Currently, the project does not support Laravel version 11.x.

#### Expected Behaviour

We expect the project to support Laravel version 11.x.

#### Steps to Reproduce

None

#### Possible Solutions

Implement support for Laravel 11.x.

### PR DESCRIPTION
**Pull request by erikn69**
Testing Laravel 11.x

Closes #907

### CODE REVIEW

**Review by parallels999 — APPROVED** [review]

**Review by fredsal — APPROVED** [review]

**Review by PaolaRuby — APPROVED** [review]

**Comment by systemsolutionweb** [comment]
@MortenDHansen @anteriovieira hi, still there??

**Comment by gonzunigad** [comment]
🙏

**Comment by parallels999** [comment]
@gonzunigad for test this change, add it to `composer.json` as `repositories` (_until it is officially merged_)
```json
"require": {
    "owen-it/laravel-auditing": "^13.0",
},
"repositories":[
    {
        "type": "vcs",
        "url": "git@github.com:erikn69/laravel-auditing.git"
    }
],
```
And then do `composer update`

**Comment by RRosalia** [comment]
@MortenDHansen @anteriovieira hi, can one of you look into this?

**Review by MortenDHansen — APPROVED** [review]

**Pull request merged**
