### PR TITLE
PHP 8.2 Build

### PR DESCRIPTION
**Pull request by erikn69**
Hi, It is only tests, no release needed

### CODE REVIEW

**Comment by parallels999** [comment]
@anteriovieira ping :)

**Comment by parallels999** [comment]
@anteriovieira ping :)

**Review by parallels999 — APPROVED** [review]

**Review by angeljqv — APPROVED** [review]

**Comment by erikn69** [comment]
@anteriovieira Hi, It is only tests, no release needed Can we merge this? thanks 👍

**Comment by LoganTFox** [comment]
Can we get this merged?

**Pull request merged**
