### PR TITLE
[2.4] Support events added

### PR DESCRIPTION
**Pull request by anteriovieira**
Laravel events provides a simple observer implementation, which allows us to subscribe and listen to events in our application.

### CODE REVIEW

**Comment by lsobral** [comment]
Can I make this change in the version that Laravel 5.1 uses?

**Comment by quetzyg** [comment]
Hi @lsobral,

What do you mean exactly? AFAIK, all versions (even this old one) fire events.

**Comment by lsobral** [comment]
I am using Laravel 5.1 and have not been able to upgrade to this new version of Auditing yet.

**Comment by quetzyg** [comment]
Ahh, gotcha! Yeah, we only support Laravel/Lumen 5.2+ on newer versions (3.x+).

Apparently, this version (2.4) is compatible with Laravel 5.1, doesn't that work for you?
Also, what's keeping you in Laravel 5.1? Just because it's a LTS version?

**Comment by lsobral** [comment]
I could not upgrade to this new version using the composer. Would it be interesting to do manually?

**Comment by lsobral** [comment]
Error Message:
Your requirements could not be resolved to an installable set of packages.

**Comment by quetzyg** [comment]
I just created a new Laravel 5.1 project and installed the 2.4 version without problems.

Here are the steps I took:
```sh
composer create-project laravel/laravel blog51 "5.1.*"
```

```sh
cd blog51
```

```sh
composer require owen-it/laravel-auditing 2.4
```

This is the output from the last command:
```sh
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing owen-it/laravel-auditing (2.4.0): Downloading (100%)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

**Comment by lsobral** [comment]
Thank you very much. I was able to update using your tip.

Another question: I need to do something for the events to work. Maybe log it?

**Comment by quetzyg** [comment]
I'm not sure I follow. You want to log the events?

**Comment by lsobral** [comment]
Eloquent Events like deleting, creating, etc. 
Thanks

**Comment by quetzyg** [comment]
You just use Laravel's event listeners for that and do whatever you see fit with the event your listening to.

**Pull request merged**
