### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by half2me**

### CODE REVIEW

**Comment by serderovsh** [comment]
++

**Comment by MrReeds** [comment]
+1

**Comment by cwilby** [comment]
I closed my PR to focus on https://github.com/owen-it/laravel-auditing/pull/581.

@RossAHC has covered namespace resolution, deprecated features, and includes documentation changes.  It's ready to merge IMO.

**Comment by half2me** [comment]
@cwilby sounds great! I'll close this then.

**Pull request closed without merging**
