### PR TITLE
[FEAT] V7 - Multi user audits

### PR DESCRIPTION
**Pull request by quetzyg**
### Description
The code in this pull request is based on #420 but with a few simplifications.

**Work done:**
- [X] Audits are now related to Users via `MorphTo`;
- [X] UserResolver now checks multiple guards to resolve Users;
- [X] Updated migration with new `user_type` column;
- [X] Updated Audit factory;
- [X] Updated tests;
- [X] Other minor cleanups;

Special thanks to [Webparking](https://github.com/Webparking) for their initial work!

@crashkonijn & @remkobrenters

### CODE REVIEW

**Comment by crashkonijn** [comment]
Awesome job, thanks!

**Comment by quetzyg** [comment]
@crashkonijn I should be tagging this in the next couple of days. Meanwhile, give it a go, to see if it works as advertised :smile:

**Comment by crashkonijn** [comment]
@quetzyg I replaced our own changes with your changes this morning and everything works perfectly!

I take it you're going to tag it with version 7, since these changes break backwards compatibility?

Also, we just made a trait which fixes these issues: https://github.com/owen-it/laravel-auditing/issues/310 by copying the fix for Laravel 5.5. Would it be an idea to include it in the package and let people add it to their models when using Laravel 5.4 or earlier?

**Comment by quetzyg** [comment]
I'm not a fan of fixing upstream issues downstream. Have you considered making a pull request to https://github.com/laravel/framework/ ?

But do share the trait, we might consider including it.

**Comment by crashkonijn** [comment]
Do they still accept PR's on versions that old?

And I understand your point, but at the same time it does have a huge impact on the performance of this package (read: almost unusable) on older Laravel versions. That's why I suggested to only include it for people to include it if they need to.

Another option could of course also be to link to this gist in the docs: https://gist.github.com/crashkonijn/7d581e55770d2379494067d8b0ce0f6d :)

**Comment by quetzyg** [comment]
>Do they still accept PR's on versions that old?

Try it, it wouldn't hurt, I guess :)

I'll have a look at the gist. :+1:

**Comment by quetzyg** [comment]
@crashkonijn https://github.com/owen-it/laravel-auditing-doc/pull/62/files#diff-73654fb858684160f86a6b76afb2a6fdR47 :wink:

**Comment by crashkonijn** [comment]
@quetzyg Awesome, thanks!

**Pull request merged**
